# Generated by Django 5.1.4 on 2025-07-05 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_area', models.CharField(max_length=100)),
                ('to_area', models.CharField(max_length=100)),
                ('time_of_travel', models.CharField(max_length=50)),
                ('time_of_reach', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('seat_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='reservationbus.trip')),
            ],
        ),
    ]
