# Generated by Django 5.1.4 on 2025-06-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
