# Generated by Django 5.1.4 on 2025-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationbus', '0002_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
