# Generated by Django 5.1.4 on 2025-07-10 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationbus', '0003_remove_user_groups_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserver_name', models.CharField(max_length=100)),
                ('seat_numbers', models.JSONField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservationbus.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
