# Generated by Django 5.1.4 on 2025-06-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationbus', '0003_remove_user_full_name_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
