# Generated by Django 5.1.4 on 2025-06-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationbus', '0005_phoneotp_remove_user_email_user_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
